server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
        routes:
          - id: 1st-service
            uri: http://localhost:50936/
            predicates:
              - Path=/first-service/**
          - id: 2nd-service
            url: http://localhost:50787/
            predicates:
              - Path:/second-service/**